#!/usr/bin/env python3
"""Render missing campaign images with local AUTOMATIC1111 API.

Requirements:
  - A1111 running locally with --api, usually http://127.0.0.1:7860
  - prompts file generated by export_campaign_missing_image_prompts.py
"""
from __future__ import annotations

import argparse
import base64
import json
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IN_JSON = ROOT / "tmp-ai-studio-missing-prompts.json"
OUT_ROOT = ROOT / "public" / "images" / "blog"


def _post_json(url: str, payload: dict) -> dict:
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=180) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _png_bytes_from_base64(s: str) -> bytes:
    # Some APIs return "data:image/png;base64,<...>"
    if "," in s and s.split(",", 1)[0].startswith("data:image"):
        s = s.split(",", 1)[1]
    return base64.b64decode(s)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--api", default="http://127.0.0.1:7860")
    parser.add_argument("--steps", type=int, default=32)
    parser.add_argument("--cfg", type=float, default=5.5)
    parser.add_argument("--sampler", default="DPM++ 2M Karras")
    parser.add_argument("--width", type=int, default=1536)
    parser.add_argument("--height", type=int, default=864)
    args = parser.parse_args()

    records = json.loads(IN_JSON.read_text(encoding="utf-8"))
    if not records:
        print("Aucune image manquante, rien a rendre.")
        return

    endpoint = f"{args.api.rstrip('/')}/sdapi/v1/txt2img"
    negative = (
        "cgi, 3d render, plastic skin, wax skin, over-sharpened, anime, cartoon, "
        "hologram, glowing UI, futuristic interface, unrealistic lens flare, deformed face"
    )

    written = 0
    for rec in records:
        slug = rec["slug"]
        out_dir = OUT_ROOT / slug
        out_dir.mkdir(parents=True, exist_ok=True)
        for slot, filename in (
            ("hero", "hero.webp"),
            ("workflow_1", "workflow-1.webp"),
            ("workflow_2", "workflow-2.webp"),
        ):
            if slot not in rec:
                continue
            payload = {
                "prompt": rec[slot],
                "negative_prompt": negative,
                "steps": args.steps,
                "cfg_scale": args.cfg,
                "sampler_name": args.sampler,
                "width": args.width,
                "height": args.height,
                "restore_faces": False,
                "enable_hr": False,
                "batch_size": 1,
                "n_iter": 1,
            }
            try:
                data = _post_json(endpoint, payload)
            except urllib.error.URLError as e:
                raise SystemExit(f"API locale indisponible: {endpoint} ({e})")
            images = data.get("images") or []
            if not images:
                raise SystemExit(f"Aucune image retournee pour {slug}:{slot}")
            png = _png_bytes_from_base64(images[0])
            tmp_png = out_dir / f"_{slot}.png"
            tmp_png.write_bytes(png)
            from PIL import Image  # local import to keep startup fast

            Image.open(tmp_png).convert("RGB").save(out_dir / filename, "WEBP", quality=90, method=6)
            tmp_png.unlink(missing_ok=True)
            print((out_dir / filename).relative_to(ROOT))
            written += 1

    print(f"Images rendues: {written}")


if __name__ == "__main__":
    main()
